"""Compile a `.lep` program into a standalone executable via PyInstaller.

This is what the original `leopard.bas`'s "Compile" button always claimed to do
but never did (IMPLEMENTATION_PLAN.md Phase 11) — bundles the script's source,
the `leopard_lang` runtime, and a small generated launcher into one
double-clickable app, with no Python install required on the machine that runs
it. Needs the optional `build` extra (`pip install -e ".[build]"`) — importing
this module doesn't require PyInstaller until `compile_program()` is actually
called, so bare-script and GUI-only installs are unaffected.

Standalone-first, same as every other layer in this project: `leopard build
script.lep` (cli.py) works with no IDE involved. The IDE's own "Build" action
(Phase 9+'s `LeopardLanguageProvider`) is a thin wrapper around this same
function — not a separate implementation.
"""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path
from typing import Optional

from .lexer import tokenize
from .parser import parse

_BARE_LAUNCHER_TEMPLATE = '''"""Auto-generated by leopard_lang.build.compile_program — do not edit."""
import sys

from leopard_lang.errors import LeopardError
from leopard_lang.interpreter import interpret
from leopard_lang.lexer import tokenize
from leopard_lang.parser import parse

SOURCE = {source!r}


def main() -> int:
    try:
        interpret(parse(tokenize(SOURCE)))
    except LeopardError as exc:
        print(exc, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

# A separate template (rather than one shared launcher with an `if program.window`
# branch) is deliberate: PyInstaller's static analysis includes every import it
# finds in the source, whether or not that branch would actually run for a given
# script — a bare-script launcher that merely *mentions*
# `leopard_lang.gui.app_host` still drags all of PyQt6 into the bundle. Keeping
# the two launchers textually separate keeps a bare-script executable lean.
_GUI_LAUNCHER_TEMPLATE = '''"""Auto-generated by leopard_lang.build.compile_program — do not edit."""
import sys

from leopard_lang.errors import LeopardError
from leopard_lang.gui.app_host import run_window
from leopard_lang.lexer import tokenize
from leopard_lang.parser import parse

SOURCE = {source!r}


def main() -> int:
    try:
        program = parse(tokenize(SOURCE))
    except LeopardError as exc:
        print(exc, file=sys.stderr)
        return 1
    try:
        run_window(program)
    except LeopardError as exc:
        print(exc, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

_GUI_HIDDEN_IMPORTS = [
    "PyQt6",
    "leopard_lang.gui.app_host",
    "leopard_lang.gui.window_builder",
    "leopard_lang.gui.properties",
    "leopard_lang.gui.events",
    "leopard_lang.gui.menus",
    "leopard_lang.gui.turtle_canvas",
    "leopard_lang.gui.text_page",
    "leopard_lang.gui.dialogs",
    "leopard_lang.gui.sound",
]


def compile_program(source: str, name: str, output_dir: Path) -> Path:
    """Compile Leopard `source` into a standalone executable named `name` under
    `output_dir/dist/`. Returns the path to the produced executable.

    Raises `LeopardSyntaxError` if `source` doesn't parse — compiling a broken
    script fails fast with a clear error instead of bundling it anyway.
    """
    program = parse(tokenize(source))  # validates before spending time on PyInstaller
    is_gui = program.window is not None
    template = _GUI_LAUNCHER_TEMPLATE if is_gui else _BARE_LAUNCHER_TEMPLATE

    import PyInstaller.__main__  # deferred: only needed here, not at import time

    with tempfile.TemporaryDirectory() as tmp:
        launcher_path = Path(tmp) / f"{name}_launcher.py"
        launcher_path.write_text(template.format(source=source), encoding="utf-8")

        args = [
            "--name", name,
            "--onefile",
            "--windowed" if is_gui else "--console",
            "--distpath", str(output_dir / "dist"),
            "--workpath", str(output_dir / "build"),
            "--specpath", str(output_dir),
            "--noconfirm",
            "--clean",
        ]
        if is_gui:
            for hidden in _GUI_HIDDEN_IMPORTS:
                args += ["--hidden-import", hidden]
        args.append(str(launcher_path))

        PyInstaller.__main__.run(args)

    exe_name = name + (".exe" if sys.platform == "win32" else "")
    return output_dir / "dist" / exe_name


def compile_file(script_path: Path, output_dir: Path, name: Optional[str] = None) -> Path:
    """Convenience wrapper: compile the `.lep` file at `script_path`."""
    source = script_path.read_text(encoding="utf-8")
    return compile_program(source, name or script_path.stem, output_dir)
